[
    {
        "bug_type": "USE_AFTER_FREE",
        "qualifier": "The call to `UI_create_method` ends up calling `BUF_strndup` (after 1 more call) and may trigger the following issue: call to `UI_create_method()` eventually accesses memory that was invalidated by call to `free()` during the call to `UI_create_method()` on line 81.",
        "severity": "ERROR",
        "line": 532,
        "column": 14,
        "procedure": "setup_ui_method",
        "procedure_start_line": 530,
        "file": "apps/apps.c",
        "bug_trace": [
            {
                "level": 0,
                "filename": "apps/apps.c",
                "line_number": 532,
                "column_number": 14,
                "description": "calling context starts here"
            },
            {
                "level": 0,
                "filename": "apps/apps.c",
                "line_number": 532,
                "column_number": 14,
                "description": "in call to `UI_create_method`"
            },
            {
                "level": 1,
                "filename": "crypto/ui/ui_lib.c",
                "line_number": 626,
                "column_number": 21,
                "description": "in call to `BUF_strdup`"
            },
            {
                "level": 2,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 66,
                "column_number": 9,
                "description": "in call to `BUF_strndup`"
            },
            {
                "level": 3,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 69,
                "column_number": 1,
                "description": "invalidation part of the trace starts here"
            },
            {
                "level": 4,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 69,
                "column_number": 1,
                "description": "parameter `str` of BUF_strndup"
            },
            {
                "level": 4,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 81,
                "column_number": 2,
                "description": "when calling `BUF_strlcpy` here"
            },
            {
                "level": 5,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 100,
                "column_number": 1,
                "description": "parameter `src` of BUF_strlcpy"
            },
            {
                "level": 5,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 110,
                "column_number": 13,
                "description": "was invalidated by call to `free()`"
            },
            {
                "level": 3,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 69,
                "column_number": 1,
                "description": "use-after-lifetime part of the trace starts here"
            },
            {
                "level": 4,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 69,
                "column_number": 1,
                "description": "parameter `str` of BUF_strndup"
            },
            {
                "level": 4,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 81,
                "column_number": 2,
                "description": "when calling `BUF_strlcpy` here"
            },
            {
                "level": 5,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 100,
                "column_number": 1,
                "description": "parameter `src` of BUF_strlcpy"
            },
            {
                "level": 5,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 103,
                "column_number": 20,
                "description": "invalid access occurs here"
            }
        ],
        "key": "apps.c|setup_ui_method|USE_AFTER_FREE",
        "hash": "e8bdd605fd99e089ec3e23a7c0ff5a51",
        "bug_type_hum": "Use After Free",
        "extras": {}
    },
    {
        "bug_type": "NULLPTR_DEREFERENCE",
        "qualifier": "`p` could be null (last assigned on line 1544) and is dereferenced in call to `BUF_strlcpy()`.",
        "severity": "ERROR",
        "line": 1545,
        "column": 2,
        "procedure": "make_config_name",
        "procedure_start_line": 1537,
        "file": "apps/apps.c",
        "bug_trace": [
            {
                "level": 1,
                "filename": "apps/apps.c",
                "line_number": 1544,
                "column_number": 4,
                "description": "in call to `CRYPTO_malloc (null case)` (modelled)"
            },
            {
                "level": 1,
                "filename": "apps/apps.c",
                "line_number": 1544,
                "column_number": 4,
                "description": "is assigned to the null pointer"
            },
            {
                "level": 1,
                "filename": "apps/apps.c",
                "line_number": 1544,
                "column_number": 2,
                "description": "assigned"
            },
            {
                "level": 1,
                "filename": "apps/apps.c",
                "line_number": 1545,
                "column_number": 2,
                "description": "when calling `BUF_strlcpy` here"
            },
            {
                "level": 2,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 100,
                "column_number": 1,
                "description": "parameter `dst` of BUF_strlcpy"
            },
            {
                "level": 2,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 109,
                "column_number": 3,
                "description": "invalid access occurs here"
            }
        ],
        "key": "apps.c|make_config_name|NULLPTR_DEREFERENCE",
        "hash": "643d327e906e45289e84d6d4f6c75a9f",
        "bug_type_hum": "Null Dereference",
        "extras": {}
    },
    {
        "bug_type": "USE_AFTER_FREE",
        "qualifier": "call to `BUF_strlcpy()` eventually accesses memory that was invalidated by call to `free()` during the call to `BUF_strlcpy()` on line 1545.",
        "severity": "ERROR",
        "line": 1545,
        "column": 2,
        "procedure": "make_config_name",
        "procedure_start_line": 1537,
        "file": "apps/apps.c",
        "bug_trace": [
            {
                "level": 0,
                "filename": "apps/apps.c",
                "line_number": 1539,
                "column_number": 16,
                "description": "invalidation part of the trace starts here"
            },
            {
                "level": 1,
                "filename": "apps/apps.c",
                "line_number": 1539,
                "column_number": 16,
                "description": "in call to `X509_get_default_cert_area`"
            },
            {
                "level": 2,
                "filename": "crypto/x509/x509_def.c",
                "line_number": 68,
                "column_number": 4,
                "description": "assigned"
            },
            {
                "level": 2,
                "filename": "crypto/x509/x509_def.c",
                "line_number": 68,
                "column_number": 4,
                "description": "returned"
            },
            {
                "level": 1,
                "filename": "apps/apps.c",
                "line_number": 1539,
                "column_number": 16,
                "description": "return from call to `X509_get_default_cert_area`"
            },
            {
                "level": 1,
                "filename": "apps/apps.c",
                "line_number": 1539,
                "column_number": 2,
                "description": "assigned"
            },
            {
                "level": 1,
                "filename": "apps/apps.c",
                "line_number": 1545,
                "column_number": 2,
                "description": "when calling `BUF_strlcpy` here"
            },
            {
                "level": 2,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 100,
                "column_number": 1,
                "description": "parameter `src` of BUF_strlcpy"
            },
            {
                "level": 2,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 110,
                "column_number": 13,
                "description": "was invalidated by call to `free()`"
            },
            {
                "level": 0,
                "filename": "apps/apps.c",
                "line_number": 1539,
                "column_number": 16,
                "description": "use-after-lifetime part of the trace starts here"
            },
            {
                "level": 1,
                "filename": "apps/apps.c",
                "line_number": 1539,
                "column_number": 16,
                "description": "in call to `X509_get_default_cert_area`"
            },
            {
                "level": 2,
                "filename": "crypto/x509/x509_def.c",
                "line_number": 68,
                "column_number": 4,
                "description": "assigned"
            },
            {
                "level": 2,
                "filename": "crypto/x509/x509_def.c",
                "line_number": 68,
                "column_number": 4,
                "description": "returned"
            },
            {
                "level": 1,
                "filename": "apps/apps.c",
                "line_number": 1539,
                "column_number": 16,
                "description": "return from call to `X509_get_default_cert_area`"
            },
            {
                "level": 1,
                "filename": "apps/apps.c",
                "line_number": 1539,
                "column_number": 2,
                "description": "assigned"
            },
            {
                "level": 1,
                "filename": "apps/apps.c",
                "line_number": 1545,
                "column_number": 2,
                "description": "when calling `BUF_strlcpy` here"
            },
            {
                "level": 2,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 100,
                "column_number": 1,
                "description": "parameter `src` of BUF_strlcpy"
            },
            {
                "level": 2,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 103,
                "column_number": 20,
                "description": "invalid access occurs here"
            }
        ],
        "key": "apps.c|make_config_name|USE_AFTER_FREE",
        "hash": "2eabde0da0d1905abdd88e3633a91269",
        "bug_type_hum": "Use After Free",
        "extras": {}
    },
    {
        "bug_type": "NULLPTR_DEREFERENCE",
        "qualifier": "`p` could be null (last assigned on line 1544) and is dereferenced in call to `BUF_strlcat()`.",
        "severity": "ERROR",
        "line": 1547,
        "column": 2,
        "procedure": "make_config_name",
        "procedure_start_line": 1537,
        "file": "apps/apps.c",
        "bug_trace": [
            {
                "level": 1,
                "filename": "apps/apps.c",
                "line_number": 1544,
                "column_number": 4,
                "description": "in call to `CRYPTO_malloc (null case)` (modelled)"
            },
            {
                "level": 1,
                "filename": "apps/apps.c",
                "line_number": 1544,
                "column_number": 4,
                "description": "is assigned to the null pointer"
            },
            {
                "level": 1,
                "filename": "apps/apps.c",
                "line_number": 1544,
                "column_number": 2,
                "description": "assigned"
            },
            {
                "level": 1,
                "filename": "apps/apps.c",
                "line_number": 1547,
                "column_number": 2,
                "description": "when calling `BUF_strlcat` here"
            },
            {
                "level": 2,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 113,
                "column_number": 1,
                "description": "parameter `dst` of BUF_strlcat"
            },
            {
                "level": 2,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 118,
                "column_number": 13,
                "description": "when calling `BUF_strlcpy` here"
            },
            {
                "level": 3,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 100,
                "column_number": 1,
                "description": "parameter `dst` of BUF_strlcpy"
            },
            {
                "level": 3,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 109,
                "column_number": 3,
                "description": "invalid access occurs here"
            }
        ],
        "key": "apps.c|make_config_name|NULLPTR_DEREFERENCE",
        "hash": "c7accd2a7daf98a415057de46d33248f",
        "bug_type_hum": "Null Dereference",
        "extras": {}
    },
    {
        "bug_type": "USE_AFTER_FREE",
        "qualifier": "The call to `BUF_strlcat` may trigger the following issue: call to `BUF_strlcat()` eventually accesses memory that was invalidated by call to `free()` during the call to `BUF_strlcat()` on line 118.",
        "severity": "ERROR",
        "line": 1547,
        "column": 2,
        "procedure": "make_config_name",
        "procedure_start_line": 1537,
        "file": "apps/apps.c",
        "bug_trace": [
            {
                "level": 0,
                "filename": "apps/apps.c",
                "line_number": 1547,
                "column_number": 2,
                "description": "calling context starts here"
            },
            {
                "level": 0,
                "filename": "apps/apps.c",
                "line_number": 1547,
                "column_number": 2,
                "description": "in call to `BUF_strlcat`"
            },
            {
                "level": 1,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 113,
                "column_number": 1,
                "description": "invalidation part of the trace starts here"
            },
            {
                "level": 2,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 113,
                "column_number": 1,
                "description": "parameter `src` of BUF_strlcat"
            },
            {
                "level": 2,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 118,
                "column_number": 13,
                "description": "when calling `BUF_strlcpy` here"
            },
            {
                "level": 3,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 100,
                "column_number": 1,
                "description": "parameter `src` of BUF_strlcpy"
            },
            {
                "level": 3,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 110,
                "column_number": 13,
                "description": "was invalidated by call to `free()`"
            },
            {
                "level": 1,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 113,
                "column_number": 1,
                "description": "use-after-lifetime part of the trace starts here"
            },
            {
                "level": 2,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 113,
                "column_number": 1,
                "description": "parameter `src` of BUF_strlcat"
            },
            {
                "level": 2,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 118,
                "column_number": 13,
                "description": "when calling `BUF_strlcpy` here"
            },
            {
                "level": 3,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 100,
                "column_number": 1,
                "description": "parameter `src` of BUF_strlcpy"
            },
            {
                "level": 3,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 103,
                "column_number": 20,
                "description": "invalid access occurs here"
            }
        ],
        "key": "apps.c|make_config_name|USE_AFTER_FREE",
        "hash": "a4fdb7f8e07dfdadf3e351287322b526",
        "bug_type_hum": "Use After Free",
        "extras": {}
    },
    {
        "bug_type": "NULLPTR_DEREFERENCE",
        "qualifier": "`p` could be null (last assigned on line 1544) and is dereferenced in call to `BUF_strlcat()`.",
        "severity": "ERROR",
        "line": 1549,
        "column": 2,
        "procedure": "make_config_name",
        "procedure_start_line": 1537,
        "file": "apps/apps.c",
        "bug_trace": [
            {
                "level": 1,
                "filename": "apps/apps.c",
                "line_number": 1544,
                "column_number": 4,
                "description": "in call to `CRYPTO_malloc (null case)` (modelled)"
            },
            {
                "level": 1,
                "filename": "apps/apps.c",
                "line_number": 1544,
                "column_number": 4,
                "description": "is assigned to the null pointer"
            },
            {
                "level": 1,
                "filename": "apps/apps.c",
                "line_number": 1544,
                "column_number": 2,
                "description": "assigned"
            },
            {
                "level": 1,
                "filename": "apps/apps.c",
                "line_number": 1549,
                "column_number": 2,
                "description": "when calling `BUF_strlcat` here"
            },
            {
                "level": 2,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 113,
                "column_number": 1,
                "description": "parameter `dst` of BUF_strlcat"
            },
            {
                "level": 2,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 118,
                "column_number": 13,
                "description": "when calling `BUF_strlcpy` here"
            },
            {
                "level": 3,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 100,
                "column_number": 1,
                "description": "parameter `dst` of BUF_strlcpy"
            },
            {
                "level": 3,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 109,
                "column_number": 3,
                "description": "invalid access occurs here"
            }
        ],
        "key": "apps.c|make_config_name|NULLPTR_DEREFERENCE",
        "hash": "c7accd2a7daf98a415057de46d33248f",
        "bug_type_hum": "Null Dereference",
        "extras": {}
    },
    {
        "bug_type": "USE_AFTER_FREE",
        "qualifier": "The call to `BUF_strlcat` may trigger the following issue: call to `BUF_strlcat()` eventually accesses memory that was invalidated by call to `free()` during the call to `BUF_strlcat()` on line 118.",
        "severity": "ERROR",
        "line": 1549,
        "column": 2,
        "procedure": "make_config_name",
        "procedure_start_line": 1537,
        "file": "apps/apps.c",
        "bug_trace": [
            {
                "level": 0,
                "filename": "apps/apps.c",
                "line_number": 1549,
                "column_number": 2,
                "description": "calling context starts here"
            },
            {
                "level": 0,
                "filename": "apps/apps.c",
                "line_number": 1549,
                "column_number": 2,
                "description": "in call to `BUF_strlcat`"
            },
            {
                "level": 1,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 113,
                "column_number": 1,
                "description": "invalidation part of the trace starts here"
            },
            {
                "level": 2,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 113,
                "column_number": 1,
                "description": "parameter `src` of BUF_strlcat"
            },
            {
                "level": 2,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 118,
                "column_number": 13,
                "description": "when calling `BUF_strlcpy` here"
            },
            {
                "level": 3,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 100,
                "column_number": 1,
                "description": "parameter `src` of BUF_strlcpy"
            },
            {
                "level": 3,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 110,
                "column_number": 13,
                "description": "was invalidated by call to `free()`"
            },
            {
                "level": 1,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 113,
                "column_number": 1,
                "description": "use-after-lifetime part of the trace starts here"
            },
            {
                "level": 2,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 113,
                "column_number": 1,
                "description": "parameter `src` of BUF_strlcat"
            },
            {
                "level": 2,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 118,
                "column_number": 13,
                "description": "when calling `BUF_strlcpy` here"
            },
            {
                "level": 3,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 100,
                "column_number": 1,
                "description": "parameter `src` of BUF_strlcpy"
            },
            {
                "level": 3,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 103,
                "column_number": 20,
                "description": "invalid access occurs here"
            }
        ],
        "key": "apps.c|make_config_name|USE_AFTER_FREE",
        "hash": "a4fdb7f8e07dfdadf3e351287322b526",
        "bug_type_hum": "Use After Free",
        "extras": {}
    },
    {
        "bug_type": "MEMORY_LEAK_C",
        "qualifier": "Memory dynamically allocated by `CRYPTO_malloc (custom malloc)` on line 245 is not freed after the last access at line 250, column 6.",
        "severity": "ERROR",
        "line": 250,
        "column": 6,
        "procedure": "i2a_ASN1_OBJECT",
        "procedure_start_line": 235,
        "file": "crypto/asn1/a_object.c",
        "bug_trace": [
            {
                "level": 0,
                "filename": "crypto/asn1/a_object.c",
                "line_number": 245,
                "column_number": 7,
                "description": "allocation part of the trace starts here"
            },
            {
                "level": 1,
                "filename": "crypto/asn1/a_object.c",
                "line_number": 245,
                "column_number": 7,
                "description": "allocated by `CRYPTO_malloc (custom malloc)` here"
            },
            {
                "level": 0,
                "filename": "crypto/asn1/a_object.c",
                "line_number": 250,
                "column_number": 6,
                "description": "memory becomes unreachable here"
            }
        ],
        "key": "a_object.c|i2a_ASN1_OBJECT|MEMORY_LEAK_C",
        "hash": "608d0a20ce08180d38d60615c48e2551",
        "bug_type_hum": "Memory Leak",
        "extras": {}
    },
    {
        "bug_type": "MEMORY_LEAK_C",
        "qualifier": "Memory dynamically allocated by `CRYPTO_malloc (custom malloc)` on line 225 is not freed after the last access at line 238, column 14.",
        "severity": "ERROR",
        "line": 238,
        "column": 14,
        "procedure": "ASN1_STRING_TABLE_add",
        "procedure_start_line": 212,
        "file": "crypto/asn1/a_strnid.c",
        "bug_trace": [
            {
                "level": 0,
                "filename": "crypto/asn1/a_strnid.c",
                "line_number": 225,
                "column_number": 9,
                "description": "allocation part of the trace starts here"
            },
            {
                "level": 1,
                "filename": "crypto/asn1/a_strnid.c",
                "line_number": 225,
                "column_number": 9,
                "description": "allocated by `CRYPTO_malloc (custom malloc)` here"
            },
            {
                "level": 0,
                "filename": "crypto/asn1/a_strnid.c",
                "line_number": 238,
                "column_number": 14,
                "description": "memory becomes unreachable here"
            }
        ],
        "key": "a_strnid.c|ASN1_STRING_TABLE_add|MEMORY_LEAK_C",
        "hash": "af9d98fd3b5470e60322e5df25a7dfac",
        "bug_type_hum": "Memory Leak",
        "extras": {}
    },
    {
        "bug_type": "MEMORY_LEAK_C",
        "qualifier": "Memory dynamically allocated by `CRYPTO_malloc (custom malloc)` on line 825 is not freed after the last access at line 829, column 7.",
        "severity": "ERROR",
        "line": 829,
        "column": 7,
        "procedure": "mime_hdr_new",
        "procedure_start_line": 800,
        "file": "crypto/asn1/asn_mime.c",
        "bug_trace": [
            {
                "level": 0,
                "filename": "crypto/asn1/asn_mime.c",
                "line_number": 825,
                "column_number": 25,
                "description": "allocation part of the trace starts here"
            },
            {
                "level": 1,
                "filename": "crypto/asn1/asn_mime.c",
                "line_number": 825,
                "column_number": 25,
                "description": "allocated by `CRYPTO_malloc (custom malloc)` here"
            },
            {
                "level": 0,
                "filename": "crypto/asn1/asn_mime.c",
                "line_number": 829,
                "column_number": 7,
                "description": "memory becomes unreachable here"
            }
        ],
        "key": "asn_mime.c|mime_hdr_new|MEMORY_LEAK_C",
        "hash": "c5749333e85986515aa2193e5911beff",
        "bug_type_hum": "Memory Leak",
        "extras": {}
    },
    {
        "bug_type": "MEMORY_LEAK_C",
        "qualifier": "Memory dynamically allocated by `CRYPTO_malloc (custom malloc)` on line 854 is not freed after the last access at line 858, column 2.",
        "severity": "ERROR",
        "line": 858,
        "column": 2,
        "procedure": "mime_hdr_addparam",
        "procedure_start_line": 833,
        "file": "crypto/asn1/asn_mime.c",
        "bug_trace": [
            {
                "level": 0,
                "filename": "crypto/asn1/asn_mime.c",
                "line_number": 854,
                "column_number": 26,
                "description": "allocation part of the trace starts here"
            },
            {
                "level": 1,
                "filename": "crypto/asn1/asn_mime.c",
                "line_number": 854,
                "column_number": 26,
                "description": "allocated by `CRYPTO_malloc (custom malloc)` here"
            },
            {
                "level": 0,
                "filename": "crypto/asn1/asn_mime.c",
                "line_number": 858,
                "column_number": 2,
                "description": "memory becomes unreachable here"
            }
        ],
        "key": "asn_mime.c|mime_hdr_addparam|MEMORY_LEAK_C",
        "hash": "bf5e5dd383e8d35eaf272a5951cb0638",
        "bug_type_hum": "Memory Leak",
        "extras": {}
    },
    {
        "bug_type": "MEMORY_LEAK_C",
        "qualifier": "Memory dynamically allocated by `CRYPTO_malloc (custom malloc)` on line 153 is not freed after the last access at line 156, column 7.",
        "severity": "ERROR",
        "line": 156,
        "column": 7,
        "procedure": "asn1_bio_new",
        "procedure_start_line": 150,
        "file": "crypto/asn1/bio_asn1.c",
        "bug_trace": [
            {
                "level": 0,
                "filename": "crypto/asn1/bio_asn1.c",
                "line_number": 153,
                "column_number": 8,
                "description": "allocation part of the trace starts here"
            },
            {
                "level": 1,
                "filename": "crypto/asn1/bio_asn1.c",
                "line_number": 153,
                "column_number": 8,
                "description": "allocated by `CRYPTO_malloc (custom malloc)` here"
            },
            {
                "level": 0,
                "filename": "crypto/asn1/bio_asn1.c",
                "line_number": 156,
                "column_number": 7,
                "description": "memory becomes unreachable here"
            }
        ],
        "key": "bio_asn1.c|asn1_bio_new|MEMORY_LEAK_C",
        "hash": "c5e3b1988bbe21d0b06ac111749c387a",
        "bug_type_hum": "Memory Leak",
        "extras": {}
    },
    {
        "bug_type": "MEMORY_LEAK_C",
        "qualifier": "Memory dynamically allocated by `CRYPTO_malloc (custom malloc)`, indirectly via call to `ASN1_STRING_type_new()` on line 68 is not freed after the last access at line 69, column 7.",
        "severity": "ERROR",
        "line": 69,
        "column": 7,
        "procedure": "ASN1_TYPE_set_octetstring",
        "procedure_start_line": 64,
        "file": "crypto/asn1/evp_asn1.c",
        "bug_trace": [
            {
                "level": 0,
                "filename": "crypto/asn1/evp_asn1.c",
                "line_number": 68,
                "column_number": 10,
                "description": "allocation part of the trace starts here"
            },
            {
                "level": 1,
                "filename": "crypto/asn1/evp_asn1.c",
                "line_number": 68,
                "column_number": 10,
                "description": "when calling `ASN1_STRING_type_new` here"
            },
            {
                "level": 2,
                "filename": "crypto/asn1/asn1_lib.c",
                "line_number": 425,
                "column_number": 21,
                "description": "allocated by `CRYPTO_malloc (custom malloc)` here"
            },
            {
                "level": 0,
                "filename": "crypto/asn1/evp_asn1.c",
                "line_number": 69,
                "column_number": 7,
                "description": "memory becomes unreachable here"
            }
        ],
        "key": "evp_asn1.c|ASN1_TYPE_set_octetstring|MEMORY_LEAK_C",
        "hash": "067553e1f948460d4687852934b5c01b",
        "bug_type_hum": "Memory Leak",
        "extras": {}
    },
    {
        "bug_type": "MEMORY_LEAK_C",
        "qualifier": "Memory dynamically allocated by `CRYPTO_malloc (custom malloc)` on line 456 is not freed after the last access at line 457, column 9.",
        "severity": "ERROR",
        "line": 457,
        "column": 9,
        "procedure": "asn1_set_seq_out",
        "procedure_start_line": 439,
        "file": "crypto/asn1/tasn_enc.c",
        "bug_trace": [
            {
                "level": 0,
                "filename": "crypto/asn1/tasn_enc.c",
                "line_number": 456,
                "column_number": 13,
                "description": "allocation part of the trace starts here"
            },
            {
                "level": 1,
                "filename": "crypto/asn1/tasn_enc.c",
                "line_number": 456,
                "column_number": 13,
                "description": "allocated by `CRYPTO_malloc (custom malloc)` here"
            },
            {
                "level": 0,
                "filename": "crypto/asn1/tasn_enc.c",
                "line_number": 457,
                "column_number": 9,
                "description": "memory becomes unreachable here"
            }
        ],
        "key": "tasn_enc.c|asn1_set_seq_out|MEMORY_LEAK_C",
        "hash": "63e13e101fb09c13d64085a2c87cfdd3",
        "bug_type_hum": "Memory Leak",
        "extras": {}
    },
    {
        "bug_type": "MEMORY_LEAK_C",
        "qualifier": "Memory dynamically allocated by `CRYPTO_malloc (custom malloc)` on line 454 is not freed after the last access at line 457, column 20.",
        "severity": "ERROR",
        "line": 457,
        "column": 20,
        "procedure": "asn1_set_seq_out",
        "procedure_start_line": 439,
        "file": "crypto/asn1/tasn_enc.c",
        "bug_trace": [
            {
                "level": 0,
                "filename": "crypto/asn1/tasn_enc.c",
                "line_number": 454,
                "column_number": 13,
                "description": "allocation part of the trace starts here"
            },
            {
                "level": 1,
                "filename": "crypto/asn1/tasn_enc.c",
                "line_number": 454,
                "column_number": 13,
                "description": "allocated by `CRYPTO_malloc (custom malloc)` here"
            },
            {
                "level": 0,
                "filename": "crypto/asn1/tasn_enc.c",
                "line_number": 457,
                "column_number": 20,
                "description": "memory becomes unreachable here"
            }
        ],
        "key": "tasn_enc.c|asn1_set_seq_out|MEMORY_LEAK_C",
        "hash": "63e13e101fb09c13d64085a2c87cfdd3",
        "bug_type_hum": "Memory Leak",
        "extras": {}
    },
    {
        "bug_type": "MEMORY_LEAK_C",
        "qualifier": "Memory dynamically allocated by `CRYPTO_malloc (custom malloc)` on line 175 is not freed after the last access at line 180, column 2.",
        "severity": "ERROR",
        "line": 180,
        "column": 2,
        "procedure": "asn1_enc_save",
        "procedure_start_line": 165,
        "file": "crypto/asn1/tasn_utl.c",
        "bug_trace": [
            {
                "level": 0,
                "filename": "crypto/asn1/tasn_utl.c",
                "line_number": 175,
                "column_number": 13,
                "description": "allocation part of the trace starts here"
            },
            {
                "level": 1,
                "filename": "crypto/asn1/tasn_utl.c",
                "line_number": 175,
                "column_number": 13,
                "description": "allocated by `CRYPTO_malloc (custom malloc)` here"
            },
            {
                "level": 0,
                "filename": "crypto/asn1/tasn_utl.c",
                "line_number": 180,
                "column_number": 2,
                "description": "memory becomes unreachable here"
            }
        ],
        "key": "tasn_utl.c|asn1_enc_save|MEMORY_LEAK_C",
        "hash": "20e3d8f0615b584ace35d9e243147ad0",
        "bug_type_hum": "Memory Leak",
        "extras": {}
    },
    {
        "bug_type": "MEMORY_LEAK_C",
        "qualifier": "Memory dynamically allocated by `CRYPTO_malloc (custom malloc)`, indirectly via call to `BN_bin2bn()` on line 132 is not freed after the last access at line 132, column 6.",
        "severity": "ERROR",
        "line": 132,
        "column": 6,
        "procedure": "bn_c2i",
        "procedure_start_line": 126,
        "file": "crypto/asn1/x_bignum.c",
        "bug_trace": [
            {
                "level": 0,
                "filename": "crypto/asn1/x_bignum.c",
                "line_number": 132,
                "column_number": 6,
                "description": "allocation part of the trace starts here"
            },
            {
                "level": 1,
                "filename": "crypto/asn1/x_bignum.c",
                "line_number": 132,
                "column_number": 6,
                "description": "when calling `BN_bin2bn` here"
            },
            {
                "level": 2,
                "filename": "crypto/bn/bn_lib.c",
                "line_number": 586,
                "column_number": 14,
                "description": "when calling `BN_new` here"
            },
            {
                "level": 3,
                "filename": "crypto/bn/bn_lib.c",
                "line_number": 283,
                "column_number": 21,
                "description": "allocated by `CRYPTO_malloc (custom malloc)` here"
            },
            {
                "level": 0,
                "filename": "crypto/asn1/x_bignum.c",
                "line_number": 132,
                "column_number": 6,
                "description": "memory becomes unreachable here"
            }
        ],
        "key": "x_bignum.c|bn_c2i|MEMORY_LEAK_C",
        "hash": "d7cab508cb774cfb101f78d4c43153cd",
        "bug_type_hum": "Memory Leak",
        "extras": {}
    },
    {
        "bug_type": "USE_AFTER_FREE",
        "qualifier": "call to `BUF_strlcpy()` eventually accesses memory that was invalidated by call to `free()` during the call to `BUF_strlcpy()` on line 237.",
        "severity": "ERROR",
        "line": 237,
        "column": 2,
        "procedure": "def_load_bio",
        "procedure_start_line": 209,
        "file": "crypto/conf/conf_def.c",
        "bug_trace": [
            {
                "level": 0,
                "filename": "crypto/conf/conf_def.c",
                "line_number": 237,
                "column_number": 2,
                "description": "invalidation part of the trace starts here"
            },
            {
                "level": 1,
                "filename": "crypto/conf/conf_def.c",
                "line_number": 237,
                "column_number": 2,
                "description": "assigned"
            },
            {
                "level": 1,
                "filename": "crypto/conf/conf_def.c",
                "line_number": 237,
                "column_number": 2,
                "description": "when calling `BUF_strlcpy` here"
            },
            {
                "level": 2,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 100,
                "column_number": 1,
                "description": "parameter `src` of BUF_strlcpy"
            },
            {
                "level": 2,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 110,
                "column_number": 13,
                "description": "was invalidated by call to `free()`"
            },
            {
                "level": 0,
                "filename": "crypto/conf/conf_def.c",
                "line_number": 237,
                "column_number": 2,
                "description": "use-after-lifetime part of the trace starts here"
            },
            {
                "level": 1,
                "filename": "crypto/conf/conf_def.c",
                "line_number": 237,
                "column_number": 2,
                "description": "assigned"
            },
            {
                "level": 1,
                "filename": "crypto/conf/conf_def.c",
                "line_number": 237,
                "column_number": 2,
                "description": "when calling `BUF_strlcpy` here"
            },
            {
                "level": 2,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 100,
                "column_number": 1,
                "description": "parameter `src` of BUF_strlcpy"
            },
            {
                "level": 2,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 103,
                "column_number": 20,
                "description": "invalid access occurs here"
            }
        ],
        "key": "conf_def.c|def_load_bio|USE_AFTER_FREE",
        "hash": "b95e082ca53573bb9510be91ab5d9452",
        "bug_type_hum": "Use After Free",
        "extras": {}
    },
    {
        "bug_type": "MEMORY_LEAK_C",
        "qualifier": "Memory dynamically allocated by `CRYPTO_malloc (custom malloc)`, indirectly via call to `BUF_strdup()` on line 304 is not freed after the last access at line 311, column 3.",
        "severity": "ERROR",
        "line": 311,
        "column": 3,
        "procedure": "module_add",
        "procedure_start_line": 291,
        "file": "crypto/conf/conf_mod.c",
        "bug_trace": [
            {
                "level": 0,
                "filename": "crypto/conf/conf_mod.c",
                "line_number": 304,
                "column_number": 15,
                "description": "allocation part of the trace starts here"
            },
            {
                "level": 1,
                "filename": "crypto/conf/conf_mod.c",
                "line_number": 304,
                "column_number": 15,
                "description": "when calling `BUF_strdup` here"
            },
            {
                "level": 2,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 66,
                "column_number": 9,
                "description": "when calling `BUF_strndup` here"
            },
            {
                "level": 3,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 75,
                "column_number": 6,
                "description": "allocated by `CRYPTO_malloc (custom malloc)` here"
            },
            {
                "level": 0,
                "filename": "crypto/conf/conf_mod.c",
                "line_number": 311,
                "column_number": 3,
                "description": "memory becomes unreachable here"
            }
        ],
        "key": "conf_mod.c|module_add|MEMORY_LEAK_C",
        "hash": "a8514c58069680e92c0f2aa803ab892e",
        "bug_type_hum": "Memory Leak",
        "extras": {}
    },
    {
        "bug_type": "USE_AFTER_FREE",
        "qualifier": "The call to `BUF_strdup` in turn calls `BUF_strndup` and may trigger the following issue: call to `BUF_strdup()` eventually accesses memory that was invalidated by call to `free()` during the call to `BUF_strdup()` on line 81.",
        "severity": "ERROR",
        "line": 553,
        "column": 10,
        "procedure": "CONF_get1_default_config_file",
        "procedure_start_line": 546,
        "file": "crypto/conf/conf_mod.c",
        "bug_trace": [
            {
                "level": 0,
                "filename": "crypto/conf/conf_mod.c",
                "line_number": 553,
                "column_number": 10,
                "description": "calling context starts here"
            },
            {
                "level": 0,
                "filename": "crypto/conf/conf_mod.c",
                "line_number": 553,
                "column_number": 10,
                "description": "in call to `BUF_strdup`"
            },
            {
                "level": 1,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 66,
                "column_number": 9,
                "description": "in call to `BUF_strndup`"
            },
            {
                "level": 2,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 69,
                "column_number": 1,
                "description": "invalidation part of the trace starts here"
            },
            {
                "level": 3,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 69,
                "column_number": 1,
                "description": "parameter `str` of BUF_strndup"
            },
            {
                "level": 3,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 81,
                "column_number": 2,
                "description": "when calling `BUF_strlcpy` here"
            },
            {
                "level": 4,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 100,
                "column_number": 1,
                "description": "parameter `src` of BUF_strlcpy"
            },
            {
                "level": 4,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 110,
                "column_number": 13,
                "description": "was invalidated by call to `free()`"
            },
            {
                "level": 2,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 69,
                "column_number": 1,
                "description": "use-after-lifetime part of the trace starts here"
            },
            {
                "level": 3,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 69,
                "column_number": 1,
                "description": "parameter `str` of BUF_strndup"
            },
            {
                "level": 3,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 81,
                "column_number": 2,
                "description": "when calling `BUF_strlcpy` here"
            },
            {
                "level": 4,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 100,
                "column_number": 1,
                "description": "parameter `src` of BUF_strlcpy"
            },
            {
                "level": 4,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 103,
                "column_number": 20,
                "description": "invalid access occurs here"
            }
        ],
        "key": "conf_mod.c|CONF_get1_default_config_file|USE_AFTER_FREE",
        "hash": "5aab0e3f5a4ab08e7b09060f8e75116b",
        "bug_type_hum": "Use After Free",
        "extras": {}
    },
    {
        "bug_type": "USE_AFTER_FREE",
        "qualifier": "call to `BUF_strlcpy()` eventually accesses memory that was invalidated by call to `free()` during the call to `BUF_strlcpy()` on line 565.",
        "severity": "ERROR",
        "line": 565,
        "column": 2,
        "procedure": "CONF_get1_default_config_file",
        "procedure_start_line": 546,
        "file": "crypto/conf/conf_mod.c",
        "bug_trace": [
            {
                "level": 0,
                "filename": "crypto/conf/conf_mod.c",
                "line_number": 565,
                "column_number": 19,
                "description": "invalidation part of the trace starts here"
            },
            {
                "level": 1,
                "filename": "crypto/conf/conf_mod.c",
                "line_number": 565,
                "column_number": 19,
                "description": "in call to `X509_get_default_cert_area`"
            },
            {
                "level": 2,
                "filename": "crypto/x509/x509_def.c",
                "line_number": 68,
                "column_number": 4,
                "description": "assigned"
            },
            {
                "level": 2,
                "filename": "crypto/x509/x509_def.c",
                "line_number": 68,
                "column_number": 4,
                "description": "returned"
            },
            {
                "level": 1,
                "filename": "crypto/conf/conf_mod.c",
                "line_number": 565,
                "column_number": 19,
                "description": "return from call to `X509_get_default_cert_area`"
            },
            {
                "level": 1,
                "filename": "crypto/conf/conf_mod.c",
                "line_number": 565,
                "column_number": 2,
                "description": "when calling `BUF_strlcpy` here"
            },
            {
                "level": 2,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 100,
                "column_number": 1,
                "description": "parameter `src` of BUF_strlcpy"
            },
            {
                "level": 2,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 110,
                "column_number": 13,
                "description": "was invalidated by call to `free()`"
            },
            {
                "level": 0,
                "filename": "crypto/conf/conf_mod.c",
                "line_number": 565,
                "column_number": 19,
                "description": "use-after-lifetime part of the trace starts here"
            },
            {
                "level": 1,
                "filename": "crypto/conf/conf_mod.c",
                "line_number": 565,
                "column_number": 19,
                "description": "in call to `X509_get_default_cert_area`"
            },
            {
                "level": 2,
                "filename": "crypto/x509/x509_def.c",
                "line_number": 68,
                "column_number": 4,
                "description": "assigned"
            },
            {
                "level": 2,
                "filename": "crypto/x509/x509_def.c",
                "line_number": 68,
                "column_number": 4,
                "description": "returned"
            },
            {
                "level": 1,
                "filename": "crypto/conf/conf_mod.c",
                "line_number": 565,
                "column_number": 19,
                "description": "return from call to `X509_get_default_cert_area`"
            },
            {
                "level": 1,
                "filename": "crypto/conf/conf_mod.c",
                "line_number": 565,
                "column_number": 2,
                "description": "when calling `BUF_strlcpy` here"
            },
            {
                "level": 2,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 100,
                "column_number": 1,
                "description": "parameter `src` of BUF_strlcpy"
            },
            {
                "level": 2,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 103,
                "column_number": 20,
                "description": "invalid access occurs here"
            }
        ],
        "key": "conf_mod.c|CONF_get1_default_config_file|USE_AFTER_FREE",
        "hash": "47dab9ec89205bd13e6d4fc52c4d731a",
        "bug_type_hum": "Use After Free",
        "extras": {}
    },
    {
        "bug_type": "USE_AFTER_FREE",
        "qualifier": "The call to `BUF_strlcat` may trigger the following issue: call to `BUF_strlcat()` eventually accesses memory that was invalidated by call to `free()` during the call to `BUF_strlcat()` on line 118.",
        "severity": "ERROR",
        "line": 567,
        "column": 2,
        "procedure": "CONF_get1_default_config_file",
        "procedure_start_line": 546,
        "file": "crypto/conf/conf_mod.c",
        "bug_trace": [
            {
                "level": 0,
                "filename": "crypto/conf/conf_mod.c",
                "line_number": 567,
                "column_number": 2,
                "description": "calling context starts here"
            },
            {
                "level": 0,
                "filename": "crypto/conf/conf_mod.c",
                "line_number": 567,
                "column_number": 2,
                "description": "in call to `BUF_strlcat`"
            },
            {
                "level": 1,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 113,
                "column_number": 1,
                "description": "invalidation part of the trace starts here"
            },
            {
                "level": 2,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 113,
                "column_number": 1,
                "description": "parameter `src` of BUF_strlcat"
            },
            {
                "level": 2,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 118,
                "column_number": 13,
                "description": "when calling `BUF_strlcpy` here"
            },
            {
                "level": 3,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 100,
                "column_number": 1,
                "description": "parameter `src` of BUF_strlcpy"
            },
            {
                "level": 3,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 110,
                "column_number": 13,
                "description": "was invalidated by call to `free()`"
            },
            {
                "level": 1,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 113,
                "column_number": 1,
                "description": "use-after-lifetime part of the trace starts here"
            },
            {
                "level": 2,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 113,
                "column_number": 1,
                "description": "parameter `src` of BUF_strlcat"
            },
            {
                "level": 2,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 118,
                "column_number": 13,
                "description": "when calling `BUF_strlcpy` here"
            },
            {
                "level": 3,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 100,
                "column_number": 1,
                "description": "parameter `src` of BUF_strlcpy"
            },
            {
                "level": 3,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 103,
                "column_number": 20,
                "description": "invalid access occurs here"
            }
        ],
        "key": "conf_mod.c|CONF_get1_default_config_file|USE_AFTER_FREE",
        "hash": "0673b25d917d67376b593fe665714301",
        "bug_type_hum": "Use After Free",
        "extras": {}
    },
    {
        "bug_type": "USE_AFTER_FREE",
        "qualifier": "The call to `BUF_strlcat` may trigger the following issue: call to `BUF_strlcat()` eventually accesses memory that was invalidated by call to `free()` during the call to `BUF_strlcat()` on line 118.",
        "severity": "ERROR",
        "line": 569,
        "column": 2,
        "procedure": "CONF_get1_default_config_file",
        "procedure_start_line": 546,
        "file": "crypto/conf/conf_mod.c",
        "bug_trace": [
            {
                "level": 0,
                "filename": "crypto/conf/conf_mod.c",
                "line_number": 569,
                "column_number": 2,
                "description": "calling context starts here"
            },
            {
                "level": 0,
                "filename": "crypto/conf/conf_mod.c",
                "line_number": 569,
                "column_number": 2,
                "description": "in call to `BUF_strlcat`"
            },
            {
                "level": 1,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 113,
                "column_number": 1,
                "description": "invalidation part of the trace starts here"
            },
            {
                "level": 2,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 113,
                "column_number": 1,
                "description": "parameter `src` of BUF_strlcat"
            },
            {
                "level": 2,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 118,
                "column_number": 13,
                "description": "when calling `BUF_strlcpy` here"
            },
            {
                "level": 3,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 100,
                "column_number": 1,
                "description": "parameter `src` of BUF_strlcpy"
            },
            {
                "level": 3,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 110,
                "column_number": 13,
                "description": "was invalidated by call to `free()`"
            },
            {
                "level": 1,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 113,
                "column_number": 1,
                "description": "use-after-lifetime part of the trace starts here"
            },
            {
                "level": 2,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 113,
                "column_number": 1,
                "description": "parameter `src` of BUF_strlcat"
            },
            {
                "level": 2,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 118,
                "column_number": 13,
                "description": "when calling `BUF_strlcpy` here"
            },
            {
                "level": 3,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 100,
                "column_number": 1,
                "description": "parameter `src` of BUF_strlcpy"
            },
            {
                "level": 3,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 103,
                "column_number": 20,
                "description": "invalid access occurs here"
            }
        ],
        "key": "conf_mod.c|CONF_get1_default_config_file|USE_AFTER_FREE",
        "hash": "0673b25d917d67376b593fe665714301",
        "bug_type_hum": "Use After Free",
        "extras": {}
    },
    {
        "bug_type": "NULLPTR_DEREFERENCE",
        "qualifier": "`q->dmax` could be null (from the call to `BN_new()` on line 128) and is dereferenced in call to `BN_set_word()`.",
        "severity": "ERROR",
        "line": 130,
        "column": 2,
        "procedure": "DH_check_pub_key",
        "procedure_start_line": 122,
        "file": "crypto/dh/dh_check.c",
        "bug_trace": [
            {
                "level": 1,
                "filename": "crypto/dh/dh_check.c",
                "line_number": 128,
                "column_number": 4,
                "description": "in call to `BN_new`"
            },
            {
                "level": 2,
                "filename": "crypto/bn/bn_lib.c",
                "line_number": 292,
                "column_number": 2,
                "description": "is assigned to the null pointer"
            },
            {
                "level": 2,
                "filename": "crypto/bn/bn_lib.c",
                "line_number": 292,
                "column_number": 2,
                "description": "assigned"
            },
            {
                "level": 1,
                "filename": "crypto/dh/dh_check.c",
                "line_number": 128,
                "column_number": 4,
                "description": "return from call to `BN_new`"
            },
            {
                "level": 1,
                "filename": "crypto/dh/dh_check.c",
                "line_number": 130,
                "column_number": 2,
                "description": "when calling `BN_set_word` here"
            },
            {
                "level": 2,
                "filename": "crypto/bn/bn_lib.c",
                "line_number": 567,
                "column_number": 1,
                "description": "parameter `a` of BN_set_word"
            },
            {
                "level": 2,
                "filename": "crypto/bn/bn_lib.c",
                "line_number": 572,
                "column_number": 2,
                "description": "invalid access occurs here"
            }
        ],
        "key": "dh_check.c|DH_check_pub_key|NULLPTR_DEREFERENCE",
        "hash": "7d9a0ff4f8337fddc1b4b9cc9e919bfa",
        "bug_type_hum": "Null Dereference",
        "extras": {}
    },
    {
        "bug_type": "MEMORY_LEAK_C",
        "qualifier": "Memory dynamically allocated by `CRYPTO_malloc (custom malloc)`, indirectly via call to `ec_pre_comp_new()` on line 779 is not freed after the last access at line 917, column 3.",
        "severity": "ERROR",
        "line": 917,
        "column": 3,
        "procedure": "ec_wNAF_precompute_mult",
        "procedure_start_line": 765,
        "file": "crypto/ec/ec_mult.c",
        "bug_trace": [
            {
                "level": 0,
                "filename": "crypto/ec/ec_mult.c",
                "line_number": 779,
                "column_number": 18,
                "description": "allocation part of the trace starts here"
            },
            {
                "level": 1,
                "filename": "crypto/ec/ec_mult.c",
                "line_number": 779,
                "column_number": 18,
                "description": "when calling `ec_pre_comp_new` here"
            },
            {
                "level": 2,
                "filename": "crypto/ec/ec_mult.c",
                "line_number": 105,
                "column_number": 23,
                "description": "allocated by `CRYPTO_malloc (custom malloc)` here"
            },
            {
                "level": 0,
                "filename": "crypto/ec/ec_mult.c",
                "line_number": 917,
                "column_number": 3,
                "description": "memory becomes unreachable here"
            }
        ],
        "key": "ec_mult.c|ec_wNAF_precompute_mult|MEMORY_LEAK_C",
        "hash": "d1be8b2e53b4d737dcb175b49f4e00da",
        "bug_type_hum": "Memory Leak",
        "extras": {}
    },
    {
        "bug_type": "MEMORY_LEAK_C",
        "qualifier": "Memory dynamically allocated by `CRYPTO_malloc (custom malloc)`, indirectly via call to `int_cleanup_item()` on line 171 is not freed after the last access at line 173, column 3.",
        "severity": "ERROR",
        "line": 173,
        "column": 3,
        "procedure": "engine_cleanup_add_first",
        "procedure_start_line": 167,
        "file": "crypto/engine/eng_lib.c",
        "bug_trace": [
            {
                "level": 0,
                "filename": "crypto/engine/eng_lib.c",
                "line_number": 171,
                "column_number": 9,
                "description": "allocation part of the trace starts here"
            },
            {
                "level": 1,
                "filename": "crypto/engine/eng_lib.c",
                "line_number": 171,
                "column_number": 9,
                "description": "when calling `int_cleanup_item` here"
            },
            {
                "level": 2,
                "filename": "crypto/engine/eng_lib.c",
                "line_number": 161,
                "column_number": 30,
                "description": "allocated by `CRYPTO_malloc (custom malloc)` here"
            },
            {
                "level": 0,
                "filename": "crypto/engine/eng_lib.c",
                "line_number": 173,
                "column_number": 3,
                "description": "memory becomes unreachable here"
            }
        ],
        "key": "eng_lib.c|engine_cleanup_add_first|MEMORY_LEAK_C",
        "hash": "5562fc9d1aca15d3de80d4a3ee82cef9",
        "bug_type_hum": "Memory Leak",
        "extras": {}
    },
    {
        "bug_type": "MEMORY_LEAK_C",
        "qualifier": "Memory dynamically allocated by `CRYPTO_malloc (custom malloc)`, indirectly via call to `int_cleanup_item()` on line 179 is not freed after the last access at line 181, column 3.",
        "severity": "ERROR",
        "line": 181,
        "column": 3,
        "procedure": "engine_cleanup_add_last",
        "procedure_start_line": 175,
        "file": "crypto/engine/eng_lib.c",
        "bug_trace": [
            {
                "level": 0,
                "filename": "crypto/engine/eng_lib.c",
                "line_number": 179,
                "column_number": 9,
                "description": "allocation part of the trace starts here"
            },
            {
                "level": 1,
                "filename": "crypto/engine/eng_lib.c",
                "line_number": 179,
                "column_number": 9,
                "description": "when calling `int_cleanup_item` here"
            },
            {
                "level": 2,
                "filename": "crypto/engine/eng_lib.c",
                "line_number": 161,
                "column_number": 30,
                "description": "allocated by `CRYPTO_malloc (custom malloc)` here"
            },
            {
                "level": 0,
                "filename": "crypto/engine/eng_lib.c",
                "line_number": 181,
                "column_number": 3,
                "description": "memory becomes unreachable here"
            }
        ],
        "key": "eng_lib.c|engine_cleanup_add_last|MEMORY_LEAK_C",
        "hash": "4ebdb2e28013c00bd10f9d8257d9d184",
        "bug_type_hum": "Memory Leak",
        "extras": {}
    },
    {
        "bug_type": "MEMORY_LEAK_C",
        "qualifier": "Memory dynamically allocated by `CRYPTO_realloc (custom realloc)`, indirectly via call to `lh_delete()` on line 424 is not freed after the last access at line 424, column 2.",
        "severity": "ERROR",
        "line": 424,
        "column": 2,
        "procedure": "int_err_del_item",
        "procedure_start_line": 413,
        "file": "crypto/err/err.c",
        "bug_trace": [
            {
                "level": 0,
                "filename": "crypto/err/err.c",
                "line_number": 424,
                "column_number": 6,
                "description": "allocation part of the trace starts here"
            },
            {
                "level": 1,
                "filename": "crypto/err/err.c",
                "line_number": 424,
                "column_number": 6,
                "description": "when calling `lh_delete` here"
            },
            {
                "level": 2,
                "filename": "crypto/lhash/lhash.c",
                "line_number": 243,
                "column_number": 3,
                "description": "when calling `contract` here"
            },
            {
                "level": 3,
                "filename": "crypto/lhash/lhash.c",
                "line_number": 374,
                "column_number": 20,
                "description": "allocated by `CRYPTO_realloc (custom realloc)` here"
            },
            {
                "level": 0,
                "filename": "crypto/err/err.c",
                "line_number": 424,
                "column_number": 2,
                "description": "memory becomes unreachable here"
            }
        ],
        "key": "err.c|int_err_del_item|MEMORY_LEAK_C",
        "hash": "1be8554e67e6353a2a0e28fe9f7a68d2",
        "bug_type_hum": "Memory Leak",
        "extras": {}
    },
    {
        "bug_type": "MEMORY_LEAK_C",
        "qualifier": "Memory dynamically allocated by `CRYPTO_malloc (custom malloc)` on line 1080 is not freed after the last access at line 1107, column 2.",
        "severity": "ERROR",
        "line": 1107,
        "column": 2,
        "procedure": "ERR_add_error_vdata",
        "procedure_start_line": 1074,
        "file": "crypto/err/err.c",
        "bug_trace": [
            {
                "level": 0,
                "filename": "crypto/err/err.c",
                "line_number": 1080,
                "column_number": 6,
                "description": "allocation part of the trace starts here"
            },
            {
                "level": 1,
                "filename": "crypto/err/err.c",
                "line_number": 1080,
                "column_number": 6,
                "description": "allocated by `CRYPTO_malloc (custom malloc)` here"
            },
            {
                "level": 0,
                "filename": "crypto/err/err.c",
                "line_number": 1107,
                "column_number": 2,
                "description": "memory becomes unreachable here"
            }
        ],
        "key": "err.c|ERR_add_error_vdata|MEMORY_LEAK_C",
        "hash": "7e44a78379e3b927195885959712a182",
        "bug_type_hum": "Memory Leak",
        "extras": {}
    },
    {
        "bug_type": "PULSE_UNINITIALIZED_VALUE",
        "qualifier": "`ctx.flags` is read without initialization during the call to `EVP_MD_CTX_set_flags()`.",
        "severity": "ERROR",
        "line": 358,
        "column": 2,
        "procedure": "EVP_Digest",
        "procedure_start_line": 351,
        "file": "crypto/evp/digest.c",
        "bug_trace": [
            {
                "level": 0,
                "filename": "crypto/evp/digest.c",
                "line_number": 351,
                "column_number": 1,
                "description": "struct field address `flags` created"
            },
            {
                "level": 0,
                "filename": "crypto/evp/digest.c",
                "line_number": 358,
                "column_number": 2,
                "description": "when calling `EVP_MD_CTX_set_flags` here"
            },
            {
                "level": 1,
                "filename": "crypto/evp/evp_lib.c",
                "line_number": 288,
                "column_number": 1,
                "description": "parameter `ctx` of EVP_MD_CTX_set_flags"
            },
            {
                "level": 1,
                "filename": "crypto/evp/evp_lib.c",
                "line_number": 290,
                "column_number": 2,
                "description": "read to uninitialized value occurs here"
            }
        ],
        "key": "digest.c|EVP_Digest|PULSE_UNINITIALIZED_VALUE",
        "hash": "fdab3c8fe2fcd7d4a63b6767957de07f",
        "bug_type_hum": "Uninitialized Value",
        "extras": {}
    },
    {
        "bug_type": "MEMORY_LEAK_C",
        "qualifier": "Memory dynamically allocated by `CRYPTO_malloc (custom malloc)` on line 241 is not freed after the last access at line 253, column 2.",
        "severity": "ERROR",
        "line": 253,
        "column": 2,
        "procedure": "EVP_PBE_alg_add_type",
        "procedure_start_line": 235,
        "file": "crypto/evp/evp_pbe.c",
        "bug_trace": [
            {
                "level": 0,
                "filename": "crypto/evp/evp_pbe.c",
                "line_number": 241,
                "column_number": 33,
                "description": "allocation part of the trace starts here"
            },
            {
                "level": 1,
                "filename": "crypto/evp/evp_pbe.c",
                "line_number": 241,
                "column_number": 33,
                "description": "allocated by `CRYPTO_malloc (custom malloc)` here"
            },
            {
                "level": 0,
                "filename": "crypto/evp/evp_pbe.c",
                "line_number": 253,
                "column_number": 2,
                "description": "memory becomes unreachable here"
            }
        ],
        "key": "evp_pbe.c|EVP_PBE_alg_add_type|MEMORY_LEAK_C",
        "hash": "001da2ee0bd3d5afca86d4c74d0e90bc",
        "bug_type_hum": "Memory Leak",
        "extras": {}
    },
    {
        "bug_type": "MEMORY_LEAK_C",
        "qualifier": "Memory dynamically allocated by `CRYPTO_malloc (custom malloc)` on line 338 is not freed after the last access at line 361, column 8.",
        "severity": "ERROR",
        "line": 361,
        "column": 8,
        "procedure": "def_add_index",
        "procedure_start_line": 333,
        "file": "crypto/ex_data.c",
        "bug_trace": [
            {
                "level": 0,
                "filename": "crypto/ex_data.c",
                "line_number": 338,
                "column_number": 52,
                "description": "allocation part of the trace starts here"
            },
            {
                "level": 1,
                "filename": "crypto/ex_data.c",
                "line_number": 338,
                "column_number": 52,
                "description": "allocated by `CRYPTO_malloc (custom malloc)` here"
            },
            {
                "level": 0,
                "filename": "crypto/ex_data.c",
                "line_number": 361,
                "column_number": 8,
                "description": "memory becomes unreachable here"
            }
        ],
        "key": "ex_data.c|def_add_index|MEMORY_LEAK_C",
        "hash": "ad50907c0fb4fb3199e46e212fae682f",
        "bug_type_hum": "Memory Leak",
        "extras": {}
    },
    {
        "bug_type": "NULLPTR_DEREFERENCE",
        "qualifier": "`ret` could be null (last assigned on line 329) and is dereferenced.",
        "severity": "ERROR",
        "line": 331,
        "column": 2,
        "procedure": "CRYPTO_strdup",
        "procedure_start_line": 327,
        "file": "crypto/mem.c",
        "bug_trace": [
            {
                "level": 1,
                "filename": "crypto/mem.c",
                "line_number": 329,
                "column_number": 14,
                "description": "in call to `CRYPTO_malloc (null case)` (modelled)"
            },
            {
                "level": 1,
                "filename": "crypto/mem.c",
                "line_number": 329,
                "column_number": 14,
                "description": "is assigned to the null pointer"
            },
            {
                "level": 1,
                "filename": "crypto/mem.c",
                "line_number": 329,
                "column_number": 2,
                "description": "assigned"
            },
            {
                "level": 1,
                "filename": "crypto/mem.c",
                "line_number": 331,
                "column_number": 2,
                "description": "invalid access occurs here"
            }
        ],
        "key": "mem.c|CRYPTO_strdup|NULLPTR_DEREFERENCE",
        "hash": "2554ec5790e547d73cadfd7243f978ec",
        "bug_type_hum": "Null Dereference",
        "extras": {}
    },
    {
        "bug_type": "NULLPTR_DEREFERENCE",
        "qualifier": "`rctx` could be null (last assigned on line 160) and is dereferenced.",
        "severity": "ERROR",
        "line": 161,
        "column": 2,
        "procedure": "OCSP_sendreq_new",
        "procedure_start_line": 154,
        "file": "crypto/ocsp/ocsp_ht.c",
        "bug_trace": [
            {
                "level": 1,
                "filename": "crypto/ocsp/ocsp_ht.c",
                "line_number": 160,
                "column_number": 9,
                "description": "in call to `CRYPTO_malloc (null case)` (modelled)"
            },
            {
                "level": 1,
                "filename": "crypto/ocsp/ocsp_ht.c",
                "line_number": 160,
                "column_number": 9,
                "description": "is assigned to the null pointer"
            },
            {
                "level": 1,
                "filename": "crypto/ocsp/ocsp_ht.c",
                "line_number": 160,
                "column_number": 2,
                "description": "assigned"
            },
            {
                "level": 1,
                "filename": "crypto/ocsp/ocsp_ht.c",
                "line_number": 161,
                "column_number": 2,
                "description": "invalid access occurs here"
            }
        ],
        "key": "ocsp_ht.c|OCSP_sendreq_new|NULLPTR_DEREFERENCE",
        "hash": "0607d388351fee5cd06eca33e1a14da5",
        "bug_type_hum": "Null Dereference",
        "extras": {}
    },
    {
        "bug_type": "MEMORY_LEAK_C",
        "qualifier": "Memory dynamically allocated by `CRYPTO_malloc (custom malloc)` on line 160 is not freed after the last access at line 170, column 7.",
        "severity": "ERROR",
        "line": 170,
        "column": 7,
        "procedure": "OCSP_sendreq_new",
        "procedure_start_line": 154,
        "file": "crypto/ocsp/ocsp_ht.c",
        "bug_trace": [
            {
                "level": 0,
                "filename": "crypto/ocsp/ocsp_ht.c",
                "line_number": 160,
                "column_number": 9,
                "description": "allocation part of the trace starts here"
            },
            {
                "level": 1,
                "filename": "crypto/ocsp/ocsp_ht.c",
                "line_number": 160,
                "column_number": 9,
                "description": "allocated by `CRYPTO_malloc (custom malloc)` here"
            },
            {
                "level": 0,
                "filename": "crypto/ocsp/ocsp_ht.c",
                "line_number": 170,
                "column_number": 7,
                "description": "memory becomes unreachable here"
            }
        ],
        "key": "ocsp_ht.c|OCSP_sendreq_new|MEMORY_LEAK_C",
        "hash": "70ca69103e808a6ec5e237cff14125ef",
        "bug_type_hum": "Memory Leak",
        "extras": {}
    },
    {
        "bug_type": "MEMORY_LEAK_C",
        "qualifier": "Memory dynamically allocated by `CRYPTO_malloc (custom malloc)` on line 340 is not freed after the last access at line 360, column 7.",
        "severity": "ERROR",
        "line": 360,
        "column": 7,
        "procedure": "X509_STORE_add_cert",
        "procedure_start_line": 334,
        "file": "crypto/x509/x509_lu.c",
        "bug_trace": [
            {
                "level": 0,
                "filename": "crypto/x509/x509_lu.c",
                "line_number": 340,
                "column_number": 21,
                "description": "allocation part of the trace starts here"
            },
            {
                "level": 1,
                "filename": "crypto/x509/x509_lu.c",
                "line_number": 340,
                "column_number": 21,
                "description": "allocated by `CRYPTO_malloc (custom malloc)` here"
            },
            {
                "level": 0,
                "filename": "crypto/x509/x509_lu.c",
                "line_number": 360,
                "column_number": 7,
                "description": "memory becomes unreachable here"
            }
        ],
        "key": "x509_lu.c|X509_STORE_add_cert|MEMORY_LEAK_C",
        "hash": "adbb68c43e652724cf80f826329e7fba",
        "bug_type_hum": "Memory Leak",
        "extras": {}
    },
    {
        "bug_type": "MEMORY_LEAK_C",
        "qualifier": "Memory dynamically allocated by `CRYPTO_malloc (custom malloc)` on line 373 is not freed after the last access at line 393, column 7.",
        "severity": "ERROR",
        "line": 393,
        "column": 7,
        "procedure": "X509_STORE_add_crl",
        "procedure_start_line": 367,
        "file": "crypto/x509/x509_lu.c",
        "bug_trace": [
            {
                "level": 0,
                "filename": "crypto/x509/x509_lu.c",
                "line_number": 373,
                "column_number": 21,
                "description": "allocation part of the trace starts here"
            },
            {
                "level": 1,
                "filename": "crypto/x509/x509_lu.c",
                "line_number": 373,
                "column_number": 21,
                "description": "allocated by `CRYPTO_malloc (custom malloc)` here"
            },
            {
                "level": 0,
                "filename": "crypto/x509/x509_lu.c",
                "line_number": 393,
                "column_number": 7,
                "description": "memory becomes unreachable here"
            }
        ],
        "key": "x509_lu.c|X509_STORE_add_crl|MEMORY_LEAK_C",
        "hash": "fed0cda3d8d11db75a3666020f08763d",
        "bug_type_hum": "Memory Leak",
        "extras": {}
    },
    {
        "bug_type": "MEMORY_LEAK_C",
        "qualifier": "Memory dynamically allocated by `CRYPTO_malloc (custom malloc)`, indirectly via call to `BUF_strdup()` on line 182 is not freed after the last access at line 197, column 5.",
        "severity": "ERROR",
        "line": 197,
        "column": 5,
        "procedure": "X509_TRUST_add",
        "procedure_start_line": 159,
        "file": "crypto/x509/x509_trs.c",
        "bug_trace": [
            {
                "level": 0,
                "filename": "crypto/x509/x509_trs.c",
                "line_number": 182,
                "column_number": 21,
                "description": "allocation part of the trace starts here"
            },
            {
                "level": 1,
                "filename": "crypto/x509/x509_trs.c",
                "line_number": 182,
                "column_number": 21,
                "description": "when calling `BUF_strdup` here"
            },
            {
                "level": 2,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 66,
                "column_number": 9,
                "description": "when calling `BUF_strndup` here"
            },
            {
                "level": 3,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 75,
                "column_number": 6,
                "description": "allocated by `CRYPTO_malloc (custom malloc)` here"
            },
            {
                "level": 0,
                "filename": "crypto/x509/x509_trs.c",
                "line_number": 197,
                "column_number": 5,
                "description": "memory becomes unreachable here"
            }
        ],
        "key": "x509_trs.c|X509_TRUST_add|MEMORY_LEAK_C",
        "hash": "e998f08de24c4ea4210f47c8266ae671",
        "bug_type_hum": "Memory Leak",
        "extras": {}
    },
    {
        "bug_type": "NULLPTR_DEREFERENCE",
        "qualifier": "`param` could be null (last assigned on line 91) and is dereferenced.",
        "severity": "ERROR",
        "line": 92,
        "column": 2,
        "procedure": "X509_VERIFY_PARAM_new",
        "procedure_start_line": 88,
        "file": "crypto/x509/x509_vpm.c",
        "bug_trace": [
            {
                "level": 1,
                "filename": "crypto/x509/x509_vpm.c",
                "line_number": 91,
                "column_number": 10,
                "description": "in call to `CRYPTO_malloc (null case)` (modelled)"
            },
            {
                "level": 1,
                "filename": "crypto/x509/x509_vpm.c",
                "line_number": 91,
                "column_number": 10,
                "description": "is assigned to the null pointer"
            },
            {
                "level": 1,
                "filename": "crypto/x509/x509_vpm.c",
                "line_number": 91,
                "column_number": 2,
                "description": "assigned"
            },
            {
                "level": 1,
                "filename": "crypto/x509/x509_vpm.c",
                "line_number": 92,
                "column_number": 2,
                "description": "invalid access occurs here"
            }
        ],
        "key": "x509_vpm.c|X509_VERIFY_PARAM_new|NULLPTR_DEREFERENCE",
        "hash": "5dafa827bb8de9814f617e1ca6135c82",
        "bug_type_hum": "Null Dereference",
        "extras": {}
    },
    {
        "bug_type": "NULLPTR_DEREFERENCE",
        "qualifier": "`node` could be null (from the call to `sk_value()` on line 453) and is dereferenced in call to `tree_link_unmatched()`.",
        "severity": "ERROR",
        "line": 455,
        "column": 8,
        "procedure": "tree_link_any",
        "procedure_start_line": 442,
        "file": "crypto/x509v3/pcy_tree.c",
        "bug_trace": [
            {
                "level": 1,
                "filename": "crypto/x509v3/pcy_tree.c",
                "line_number": 453,
                "column_number": 10,
                "description": "in call to `sk_value`"
            },
            {
                "level": 2,
                "filename": "crypto/stack/stack.c",
                "line_number": 300,
                "column_number": 1,
                "description": "parameter `st` of sk_value"
            },
            {
                "level": 2,
                "filename": "crypto/stack/stack.c",
                "line_number": 302,
                "column_number": 6,
                "description": "taking \"else\" branch"
            },
            {
                "level": 2,
                "filename": "crypto/stack/stack.c",
                "line_number": 302,
                "column_number": 13,
                "description": "taking \"else\" branch"
            },
            {
                "level": 2,
                "filename": "crypto/stack/stack.c",
                "line_number": 302,
                "column_number": 24,
                "description": "taking \"then\" branch"
            },
            {
                "level": 2,
                "filename": "crypto/stack/stack.c",
                "line_number": 302,
                "column_number": 39,
                "description": "is assigned to the null pointer"
            },
            {
                "level": 2,
                "filename": "crypto/stack/stack.c",
                "line_number": 302,
                "column_number": 39,
                "description": "returned"
            },
            {
                "level": 1,
                "filename": "crypto/x509v3/pcy_tree.c",
                "line_number": 453,
                "column_number": 10,
                "description": "return from call to `sk_value`"
            },
            {
                "level": 1,
                "filename": "crypto/x509v3/pcy_tree.c",
                "line_number": 453,
                "column_number": 3,
                "description": "assigned"
            },
            {
                "level": 1,
                "filename": "crypto/x509v3/pcy_tree.c",
                "line_number": 455,
                "column_number": 8,
                "description": "when calling `tree_link_unmatched` here"
            },
            {
                "level": 2,
                "filename": "crypto/x509v3/pcy_tree.c",
                "line_number": 402,
                "column_number": 1,
                "description": "parameter `node` of tree_link_unmatched"
            },
            {
                "level": 2,
                "filename": "crypto/x509v3/pcy_tree.c",
                "line_number": 411,
                "column_number": 8,
                "description": "invalid access occurs here"
            }
        ],
        "key": "pcy_tree.c|tree_link_any|NULLPTR_DEREFERENCE",
        "hash": "224eab39268302eb78df7d6d62d61b61",
        "bug_type_hum": "Null Dereference",
        "extras": {}
    },
    {
        "bug_type": "MEMORY_LEAK_C",
        "qualifier": "Memory dynamically allocated by `CRYPTO_malloc (custom malloc)`, indirectly via call to `BUF_strdup()` on line 200 is not freed after the last access at line 216, column 5.",
        "severity": "ERROR",
        "line": 216,
        "column": 5,
        "procedure": "X509_PURPOSE_add",
        "procedure_start_line": 172,
        "file": "crypto/x509v3/v3_purp.c",
        "bug_trace": [
            {
                "level": 0,
                "filename": "crypto/x509v3/v3_purp.c",
                "line_number": 200,
                "column_number": 16,
                "description": "allocation part of the trace starts here"
            },
            {
                "level": 1,
                "filename": "crypto/x509v3/v3_purp.c",
                "line_number": 200,
                "column_number": 16,
                "description": "when calling `BUF_strdup` here"
            },
            {
                "level": 2,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 66,
                "column_number": 9,
                "description": "when calling `BUF_strndup` here"
            },
            {
                "level": 3,
                "filename": "crypto/buffer/buf_str.c",
                "line_number": 75,
                "column_number": 6,
                "description": "allocated by `CRYPTO_malloc (custom malloc)` here"
            },
            {
                "level": 0,
                "filename": "crypto/x509v3/v3_purp.c",
                "line_number": 216,
                "column_number": 5,
                "description": "memory becomes unreachable here"
            }
        ],
        "key": "v3_purp.c|X509_PURPOSE_add|MEMORY_LEAK_C",
        "hash": "d27a328af53d0abf77ea6c95a75e930a",
        "bug_type_hum": "Memory Leak",
        "extras": {}
    },
    {
        "bug_type": "MEMORY_LEAK_C",
        "qualifier": "Memory dynamically allocated by `CRYPTO_malloc (custom malloc)` on line 26 is not freed after the last access at line 35, column 3.",
        "severity": "ERROR",
        "line": 35,
        "column": 3,
        "procedure": "pkey_gost_init",
        "procedure_start_line": 22,
        "file": "engines/ccgost/gost_pmeth.c",
        "bug_trace": [
            {
                "level": 0,
                "filename": "engines/ccgost/gost_pmeth.c",
                "line_number": 26,
                "column_number": 9,
                "description": "allocation part of the trace starts here"
            },
            {
                "level": 1,
                "filename": "engines/ccgost/gost_pmeth.c",
                "line_number": 26,
                "column_number": 9,
                "description": "allocated by `CRYPTO_malloc (custom malloc)` here"
            },
            {
                "level": 0,
                "filename": "engines/ccgost/gost_pmeth.c",
                "line_number": 35,
                "column_number": 3,
                "description": "memory becomes unreachable here"
            }
        ],
        "key": "gost_pmeth.c|pkey_gost_init|MEMORY_LEAK_C",
        "hash": "2a495e8f7efdaf11ae43c94f549634c2",
        "bug_type_hum": "Memory Leak",
        "extras": {}
    },
    {
        "bug_type": "PULSE_UNINITIALIZED_VALUE",
        "qualifier": "`_.dmax` is read without initialization.",
        "severity": "ERROR",
        "line": 828,
        "column": 6,
        "procedure": "ubsec_dsa_verify",
        "procedure_start_line": 818,
        "file": "engines/e_ubsec.c",
        "bug_trace": [
            {
                "level": 0,
                "filename": "engines/e_ubsec.c",
                "line_number": 818,
                "column_number": 1,
                "description": "struct field address `dmax` created"
            },
            {
                "level": 0,
                "filename": "engines/e_ubsec.c",
                "line_number": 828,
                "column_number": 6,
                "description": "read to uninitialized value occurs here"
            }
        ],
        "key": "e_ubsec.c|ubsec_dsa_verify|PULSE_UNINITIALIZED_VALUE",
        "hash": "aa2bb76c5b5897123774b22a8556b091",
        "bug_type_hum": "Uninitialized Value",
        "extras": {}
    },
    {
        "bug_type": "NULLPTR_DEREFERENCE",
        "qualifier": "`frag` could be null (from the call to `dtls1_hm_fragment_new()` on line 1181) and is dereferenced.",
        "severity": "ERROR",
        "line": 1183,
        "column": 9,
        "procedure": "dtls1_buffer_message",
        "procedure_start_line": 1171,
        "file": "ssl/d1_both.c",
        "bug_trace": [
            {
                "level": 1,
                "filename": "ssl/d1_both.c",
                "line_number": 1181,
                "column_number": 9,
                "description": "in call to `dtls1_hm_fragment_new`"
            },
            {
                "level": 2,
                "filename": "ssl/d1_both.c",
                "line_number": 179,
                "column_number": 24,
                "description": "in call to `CRYPTO_malloc (null case)` (modelled)"
            },
            {
                "level": 2,
                "filename": "ssl/d1_both.c",
                "line_number": 179,
                "column_number": 24,
                "description": "is assigned to the null pointer"
            },
            {
                "level": 2,
                "filename": "ssl/d1_both.c",
                "line_number": 179,
                "column_number": 2,
                "description": "assigned"
            },
            {
                "level": 2,
                "filename": "ssl/d1_both.c",
                "line_number": 180,
                "column_number": 7,
                "description": "taking \"then\" branch"
            },
            {
                "level": 2,
                "filename": "ssl/d1_both.c",
                "line_number": 181,
                "column_number": 3,
                "description": "is assigned to the null pointer"
            },
            {
                "level": 2,
                "filename": "ssl/d1_both.c",
                "line_number": 181,
                "column_number": 3,
                "description": "returned"
            },
            {
                "level": 1,
                "filename": "ssl/d1_both.c",
                "line_number": 1181,
                "column_number": 9,
                "description": "return from call to `dtls1_hm_fragment_new`"
            },
            {
                "level": 1,
                "filename": "ssl/d1_both.c",
                "line_number": 1181,
                "column_number": 2,
                "description": "assigned"
            },
            {
                "level": 1,
                "filename": "ssl/d1_both.c",
                "line_number": 1183,
                "column_number": 9,
                "description": "invalid access occurs here"
            }
        ],
        "key": "d1_both.c|dtls1_buffer_message|NULLPTR_DEREFERENCE",
        "hash": "40e16234ea7c72177a9976859d55b8d5",
        "bug_type_hum": "Null Dereference",
        "extras": {}
    },
    {
        "bug_type": "MEMORY_LEAK_C",
        "qualifier": "Memory dynamically allocated by `CRYPTO_malloc (custom malloc)`, indirectly via call to `pitem_new()` on line 1216 is not freed after the last access at line 1229, column 2.",
        "severity": "ERROR",
        "line": 1229,
        "column": 2,
        "procedure": "dtls1_buffer_message",
        "procedure_start_line": 1171,
        "file": "ssl/d1_both.c",
        "bug_trace": [
            {
                "level": 0,
                "filename": "ssl/d1_both.c",
                "line_number": 1216,
                "column_number": 9,
                "description": "allocation part of the trace starts here"
            },
            {
                "level": 1,
                "filename": "ssl/d1_both.c",
                "line_number": 1216,
                "column_number": 9,
                "description": "when calling `pitem_new` here"
            },
            {
                "level": 2,
                "filename": "crypto/pqueue/pqueue.c",
                "line_number": 73,
                "column_number": 26,
                "description": "allocated by `CRYPTO_malloc (custom malloc)` here"
            },
            {
                "level": 0,
                "filename": "ssl/d1_both.c",
                "line_number": 1229,
                "column_number": 2,
                "description": "memory becomes unreachable here"
            }
        ],
        "key": "d1_both.c|dtls1_buffer_message|MEMORY_LEAK_C",
        "hash": "2a86a83d35fc41568144df9376831bca",
        "bug_type_hum": "Memory Leak",
        "extras": {}
    },
    {
        "bug_type": "USE_AFTER_FREE",
        "qualifier": "call to `ssl2_clear()` eventually accesses memory that was invalidated by call to `free()` during the call to `ssl2_clear()` on line 338.",
        "severity": "ERROR",
        "line": 338,
        "column": 2,
        "procedure": "ssl2_new",
        "procedure_start_line": 319,
        "file": "ssl/s2_lib.c",
        "bug_trace": [
            {
                "level": 0,
                "filename": "ssl/s2_lib.c",
                "line_number": 323,
                "column_number": 10,
                "description": "invalidation part of the trace starts here"
            },
            {
                "level": 1,
                "filename": "ssl/s2_lib.c",
                "line_number": 323,
                "column_number": 10,
                "description": "allocated by call to `CRYPTO_malloc` (modelled)"
            },
            {
                "level": 1,
                "filename": "ssl/s2_lib.c",
                "line_number": 323,
                "column_number": 7,
                "description": "assigned"
            },
            {
                "level": 1,
                "filename": "ssl/s2_lib.c",
                "line_number": 336,
                "column_number": 2,
                "description": "assigned"
            },
            {
                "level": 1,
                "filename": "ssl/s2_lib.c",
                "line_number": 338,
                "column_number": 2,
                "description": "when calling `ssl2_clear` here"
            },
            {
                "level": 2,
                "filename": "ssl/s2_lib.c",
                "line_number": 365,
                "column_number": 1,
                "description": "parameter `s` of ssl2_clear"
            },
            {
                "level": 2,
                "filename": "ssl/s2_lib.c",
                "line_number": 370,
                "column_number": 2,
                "description": "assigned"
            },
            {
                "level": 2,
                "filename": "ssl/s2_lib.c",
                "line_number": 375,
                "column_number": 2,
                "description": "was invalidated by call to `free()`"
            },
            {
                "level": 0,
                "filename": "ssl/s2_lib.c",
                "line_number": 323,
                "column_number": 10,
                "description": "use-after-lifetime part of the trace starts here"
            },
            {
                "level": 1,
                "filename": "ssl/s2_lib.c",
                "line_number": 323,
                "column_number": 10,
                "description": "allocated by call to `CRYPTO_malloc` (modelled)"
            },
            {
                "level": 1,
                "filename": "ssl/s2_lib.c",
                "line_number": 323,
                "column_number": 7,
                "description": "assigned"
            },
            {
                "level": 1,
                "filename": "ssl/s2_lib.c",
                "line_number": 336,
                "column_number": 2,
                "description": "assigned"
            },
            {
                "level": 1,
                "filename": "ssl/s2_lib.c",
                "line_number": 338,
                "column_number": 2,
                "description": "when calling `ssl2_clear` here"
            },
            {
                "level": 2,
                "filename": "ssl/s2_lib.c",
                "line_number": 365,
                "column_number": 1,
                "description": "parameter `s` of ssl2_clear"
            },
            {
                "level": 2,
                "filename": "ssl/s2_lib.c",
                "line_number": 370,
                "column_number": 2,
                "description": "assigned"
            },
            {
                "level": 2,
                "filename": "ssl/s2_lib.c",
                "line_number": 372,
                "column_number": 7,
                "description": "invalid access occurs here"
            }
        ],
        "key": "s2_lib.c|ssl2_new|USE_AFTER_FREE",
        "hash": "479732ac4b3efb5de13607fbaf05eb0e",
        "bug_type_hum": "Use After Free",
        "extras": {}
    },
    {
        "bug_type": "PULSE_UNINITIALIZED_VALUE",
        "qualifier": "`ctx.flags` is read without initialization during the call to `EVP_MD_CTX_set_flags()`.",
        "severity": "ERROR",
        "line": 173,
        "column": 2,
        "procedure": "ssl3_generate_key_block",
        "procedure_start_line": 160,
        "file": "ssl/s3_enc.c",
        "bug_trace": [
            {
                "level": 0,
                "filename": "ssl/s3_enc.c",
                "line_number": 160,
                "column_number": 1,
                "description": "struct field address `flags` created"
            },
            {
                "level": 0,
                "filename": "ssl/s3_enc.c",
                "line_number": 173,
                "column_number": 2,
                "description": "when calling `EVP_MD_CTX_set_flags` here"
            },
            {
                "level": 1,
                "filename": "crypto/evp/evp_lib.c",
                "line_number": 288,
                "column_number": 1,
                "description": "parameter `ctx` of EVP_MD_CTX_set_flags"
            },
            {
                "level": 1,
                "filename": "crypto/evp/evp_lib.c",
                "line_number": 290,
                "column_number": 2,
                "description": "read to uninitialized value occurs here"
            }
        ],
        "key": "s3_enc.c|ssl3_generate_key_block|PULSE_UNINITIALIZED_VALUE",
        "hash": "b81e6f8c8363fe5ecd44b61641a2bdbd",
        "bug_type_hum": "Uninitialized Value",
        "extras": {}
    },
    {
        "bug_type": "USE_AFTER_FREE",
        "qualifier": "The call to `RAND_pseudo_bytes` ends up calling `CRYPTO_THREADID_current` (after 5 more calls) and may trigger the following issue: call to `RAND_pseudo_bytes()` eventually accesses memory that was invalidated by call to `free()` during the call to `RAND_pseudo_bytes()` on line 507.",
        "severity": "ERROR",
        "line": 300,
        "column": 2,
        "procedure": "main",
        "procedure_start_line": 283,
        "file": "test/igetest.c",
        "bug_trace": [
            {
                "level": 0,
                "filename": "test/igetest.c",
                "line_number": 300,
                "column_number": 2,
                "description": "calling context starts here"
            },
            {
                "level": 0,
                "filename": "test/igetest.c",
                "line_number": 300,
                "column_number": 2,
                "description": "in call to `RAND_pseudo_bytes`"
            },
            {
                "level": 1,
                "filename": "crypto/rand/rand_lib.c",
                "line_number": 170,
                "column_number": 28,
                "description": "in call to `RAND_get_rand_method`"
            },
            {
                "level": 2,
                "filename": "crypto/rand/rand_lib.c",
                "line_number": 97,
                "column_number": 15,
                "description": "in call to `ENGINE_get_default_RAND`"
            },
            {
                "level": 3,
                "filename": "crypto/engine/tb_rand.c",
                "line_number": 104,
                "column_number": 9,
                "description": "in call to `engine_table_select`"
            },
            {
                "level": 4,
                "filename": "crypto/engine/eng_table.c",
                "line_number": 257,
                "column_number": 2,
                "description": "in call to `ERR_set_mark`"
            },
            {
                "level": 5,
                "filename": "crypto/err/err.c",
                "line_number": 1114,
                "column_number": 5,
                "description": "in call to `ERR_get_state`"
            },
            {
                "level": 6,
                "filename": "crypto/err/err.c",
                "line_number": 1012,
                "column_number": 2,
                "description": "in call to `CRYPTO_THREADID_current`"
            },
            {
                "level": 7,
                "filename": "crypto/cryptlib.c",
                "line_number": 483,
                "column_number": 1,
                "description": "invalidation part of the trace starts here"
            },
            {
                "level": 8,
                "filename": "crypto/cryptlib.c",
                "line_number": 483,
                "column_number": 1,
                "description": "parameter `id` of CRYPTO_THREADID_current"
            },
            {
                "level": 8,
                "filename": "crypto/cryptlib.c",
                "line_number": 507,
                "column_number": 2,
                "description": "when calling `CRYPTO_THREADID_set_pointer` here"
            },
            {
                "level": 9,
                "filename": "crypto/cryptlib.c",
                "line_number": 435,
                "column_number": 1,
                "description": "parameter `id` of CRYPTO_THREADID_set_pointer"
            },
            {
                "level": 9,
                "filename": "crypto/cryptlib.c",
                "line_number": 441,
                "column_number": 2,
                "description": "was invalidated by call to `free()`"
            },
            {
                "level": 7,
                "filename": "crypto/cryptlib.c",
                "line_number": 483,
                "column_number": 1,
                "description": "use-after-lifetime part of the trace starts here"
            },
            {
                "level": 8,
                "filename": "crypto/cryptlib.c",
                "line_number": 483,
                "column_number": 1,
                "description": "parameter `id` of CRYPTO_THREADID_current"
            },
            {
                "level": 8,
                "filename": "crypto/cryptlib.c",
                "line_number": 507,
                "column_number": 2,
                "description": "when calling `CRYPTO_THREADID_set_pointer` here"
            },
            {
                "level": 9,
                "filename": "crypto/cryptlib.c",
                "line_number": 435,
                "column_number": 1,
                "description": "parameter `id` of CRYPTO_THREADID_set_pointer"
            },
            {
                "level": 9,
                "filename": "crypto/cryptlib.c",
                "line_number": 437,
                "column_number": 2,
                "description": "invalid access occurs here"
            }
        ],
        "key": "igetest.c|main|USE_AFTER_FREE",
        "hash": "3cdf486e9b8cfc8e83e047a8d7623936",
        "bug_type_hum": "Use After Free",
        "extras": {}
    }
]
